Amir feedback
opensafely/documentation pull request #200
Opened 2021-03-25 13:38 UTC by sebbacon

2021-03-25 13:44 UTC, bloodearnest requested changes

2021-03-25 13:44 UTC, bloodearnest commented on docs/getting-started.md
> +   `opensafely pull --force`.  The first time you run it, this can take a very
I would remove this step entirely. `opensafely run` will download any images it needs.  There's no need to force the user to download every image (~10Gb) when they are only going to use `cohortextractor` image (~1GB) in this getting started guide.

If you really want to pre-load it, do `opensafely pull cohortextractor`

2021-06-16 08:35 UTC, ghickman commented
I've updated this to take into account feedback, some tweaks to make editing (particularly inserting into lists) easier, and based it on the current state of `master`.  One of the paragraphs from the original changeset has already been rolled in (noting there are two backends).

@StevenMaude – you're probably best to review this?

2021-06-16 09:24 UTC, StevenMaude approved these changes

2021-06-16 09:27 UTC, merged