Document Requesting Futher R Dependencies
opensafely/documentation pull request #44
Opened 2020-11-27 17:09 UTC by ghickman

This adds a page, "Working with R", to document the process for requesting more dependencies in our R image.

I've used the name "Working with R" on the basis that further R specific docs can go in there and we can have matching Python and Stata pages. 

Is there a better place in the nav for this to live?

Fixes #43

2020-11-27 19:22 UTC, sebbacon requested changes
I think you've forgotten to commit someting...

2020-11-27 20:13 UTC, wjchulme commented
(once you've added this actual `working-with-R.md`) I'm happy for this to stay where it is for now and I'll think about how best to organise once other docs are in place.

2020-11-30 09:05 UTC, ghickman commented
This might be the most definitive Friday Afternoon PR I've ever made…

2020-11-30 12:00 UTC, wjchulme approved these changes

2020-11-30 12:01 UTC, merged